Lab5
aadereiko/up pull request #6
Opened 2018-04-04 13:05 UTC by aadereiko

2018-04-04 21:11 UTC, ala-n requested changes

2018-04-04 21:11 UTC, ala-n commented on UI/index.html
> +    <div class ="downloadYet"> <img src="./pictures/downloadYet.png" class ="downloadYet" alt ="Загрузить еще"></div>
Минутка английского yet - это больше относительно времени происходящего 
(I didn't read it yet. - Я это ЕЩЕ не прочитал.)
Здесь downloadMore 
И как по мне кнопке не место в контейнере с постами

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +let USER_AUTHORIZED = "Djadka.by";
В upper case называем контанты, сфигали это константа?

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +let jsFunctions  = function () {
Название... не несет смысла в контексте понимания что это такое
С точки зрения языка что это и так видно ))

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +let USER_AUTHORIZED = "Djadka.by";
И что-то мне подсказывает что половина если не все переменные здесь - часть модуля.
Модуль не должен иметь сайд эффектов если он меняет (использует) переменную - то она часть модуля и не должна она просто в window валятся.

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +            if (result.length < top) {
Ага, не понял...те от skip исключительной ситуации не бывает...
не выдумываем исключительная ситуация может быть только одна выборка с учетом фильтра либо пустая либо не содержит кусток [skip, skip + top] и тогда результат пустой массив.

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +            return result.slice(skip, top);
skip, skip + top
под top здесь подразумевалось кол-во

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +                result.filter(function (post) {
1) А нет ли смысла это сделать раньше дабы сократить выборку до фильтров
2) А если фильтра нет то мы возвращаем удаленные ....

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +                        for (let i = 0; i < filterConfing.hashtags.length; i++) {
PS: Cosmetic но вообще говоря внешний цикл тоже some

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +                return parseInt(elem.id) == id;
Ага, либо используем === и думаем про приведение, либо оставляем == и не занимаемся приведением самостоятельно.

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +            if (parseInt(post.id) !== NaN) {
На некоторых проектах в правилах eslint (автоматическая проверка качества и стандартизации (общий стиль) кода) стоит уровень вложенности не более ~4 и я вполне одобряю такой подход 
черт ногу сломит в этих ветвях. 
Проще... то что просто - оно с большей вероятностью не сломется.

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +            if (jsFunctions.validatePhotoPost(post) === true) {
булеан не надо сравнивать булеан сам по себеи истина или ложь

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +            if(post)
скобочки!!!

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +                for(let i = 0; i < post.hashtags.length; i++){
Так... вот смотри, не придирка просто говорю как человек с опытом который много чего в коде видел.
На 317 строчке я потерял нить и мне нужно перечитывать все снова, эффект очень простой: код вызывет эмоции "я не хочу знать что тут происходит", "я не хочу это понимать и читать", "это не хочется фиксить если что, а хочется переписать" и т.п.
Да, понятно, тебе понадобилась какая-то доп логика, но сделай так чтобы она была понятна даже тому человеку, который вообще не в теме и увидел только отрывок твоего кода.
Код должен читаться!! 
Выноси логику в отдельные функции (называй их понятно), переменные тоже максимально понятно называй. Если что-то творишь сложное оставь коментарий что ты делаешь. 
Тебе потом коллеги спасибо скажут за то что они не провели вечер мучительно пытаясь понять что у тебя в коде происходило.

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +    function compareHash(a, b) {
И снова здавствуйте а это каким боком работа с DOM ?

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +    let downloadYet = document.querySelector(".downloadYet");
loadMoreBtn - и нету вопросов что это такое...

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +    let postsHTML = document.querySelector(".posts");
Ну это не HTML это элемент, а точнее нам важно что это контейнер

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +            let br = document.createElement("br");
Ох... ну 100 раз говорил уже
br это типографический тег он для текста!!!
если мы юзаем его (да еще и несколько раз) для разметки это костыль !!!

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +        if (hashtags.length != 0) {
а дальше разметка поплыла

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +        if (hashtags.length != 0) {
!==
кстати!!!!!!

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +        let newDiv = document.createElement("div");
A-a-a-a-a-a-a-a-a! 
Ну еперная фабрика... 
Опять же познакомтесь с TemplateString + innerHTML 
ну пожалуста! это не читабельно ну ни капли !!!!

2018-04-04 21:11 UTC, ala-n commented on UI/scrypt.js
> +        proposition[1].innerText = mapHash[0].word;
- Цикл ? 
- не не слышал...

и почему 1, 2, 3, 4 что это за сказочный трешь...

2018-04-04 21:11 UTC, ala-n commented on UI/styles.css
> +-webkit-border-radius: 3px; /*закругление углов (Google Chrome)*/
префиксы уже не совсем не нужные в 2k18
это для очень старых версий браузеров, я даже не знаю можно ли их сейчас скачать... 
если что-то юзаем то проявляем любопытство и читаем, а что это.

2018-04-04 21:11 UTC, ala-n commented on UI/styles.css
> +    -o-transition-duration: 0.8s;
вот расскажи ты хотя бы оперу 12 в глаза видел? ну помер давно браузер в том виде.
Я не снижаю оценку за это но блин не копипасти все бездумно !!!

2018-04-09 06:32 UTC, aadereiko commented on UI/scrypt.js
> +                        for (let i = 0; i < filterConfing.hashtags.length; i++) {
Вы имеете в виду, если кто-то не содержит?

2018-04-17 16:18 UTC, ala-n approved these changes

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +                        for (let i = 0; i < filterConfing.hashtags.length; i++) {
Сори. Вернее тут every
```
let hashtags = filterConfing.hashtags;
result = result.filter( (post) => 
  hashtags.every((tag) => (post.hashtags || []).includes(tag))
);
```

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +        mapHash: [],
То что мы заносим в return - аналог public свойств.
Должны ли быть public mapHash, user_authorized, да и вообще говоря photoPosts - нет
```
var Module = (function() {
// private space
const privateField;
function privateFunction() {..}
return {
// public space (obj)
publicVariable: ..,
publicMethod: function() {},
publicMethod2: privateFunction // (if privateFunction is just private declaration)
};
})();
```

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +        {
Контента не будет в последствии,
идеальный вариант чтобы он сейчас попадал примерно так:
```
ApplicationModel.addPosts([
 {/*test post 1*/}, 
 {/*test post 2*/},
...
]);
```

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +        fillMapHash: function () {
см коммент на 12 строчке, это вспомогательный метод лучше его скрыть.

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +    function compareHash(a, b) {
Это точно часть View ...?

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +            if (hashtags.length !== 0) {
return (hastags || []).map((ht) => '#' + ht).join(' ');

2018-04-17 16:18 UTC, ala-n commented on UI/scrypt.js
> +            if(ApplicationModel.user_authorized === null){
Кстати user_authorized в camelCase

2018-04-18 14:13 UTC, aadereiko commented on UI/scrypt.js
> +        mapHash: [],
я же  ими потом пользуюсь в других модулях, почему нет?

2018-04-18 14:14 UTC, aadereiko commented on UI/scrypt.js
> +        {
то есть, тут убрать массив наших фотопостов?

2018-04-18 14:14 UTC, aadereiko commented on UI/scrypt.js
> +        {
а где их тогда хранить?

2018-04-18 14:15 UTC, aadereiko commented on UI/scrypt.js
> +        fillMapHash: function () {
и тут опять же
я использую метод за пределами модуля

2018-04-18 19:41 UTC, ala-n commented on UI/scrypt.js
> +        {
Убрать не массив а его заполнение )
Значения будут хранится стначала как показано выше, аля 
//TODO: move that stabs outside
ApplicationModel.addPosts([
 {/*test post 1*/}, 
 {/*test post 2*/},
...
]);
Затем все уйдет в localStorage, а потом на Server-Side.

2018-04-18 19:45 UTC, ala-n commented on UI/scrypt.js
> +        mapHash: [],
А вот это хороший вопрос зачем он нужен тебе в других модулях в таком виде.
Так или иначе не хорошо светить наружу что-то внутреннеее или необработанное.
(внешне я вижу эту пременную так)
Нужен результат обработки этой мапы - сделай публичный метод С ПОНЯТНЫМ НАЗВЕНИЕМ и возвращай там результат обработки этой пременной.

2024-11-26 08:07 UTC, closed without merging